### ISSUE TITLE
Mettre en place l'ingration continue avec une appli rails vide

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet-back-P2019#1]
Créer une application rails vide: `rails new .`
https://guides.rubyonrails.org/getting_started.html

commiter et remonter cette appli dans github

créer le fichier de paramétrage de travis:
https://github.com/travis-ci/travis.rb#init
https://github.com/travis-ci/travis.rb#installation

Poster en commentaire ici le lien vers votre CI et votre github

**Comment by GRazafy** [comment]
Gabriel Razafindratsima

CI: https://travis-ci.org/GRazafy/LPA2/builds/496964123

Github: https://github.com/GRazafy/LPA2

edit: mauvais build

**Comment by Skaopap** [comment]
CI : https://travis-ci.org/Skaopap/UTBM_WORK/builds/496963518

github : https://github.com/Skaopap

**Comment by Swyfee** [comment]
CI: https://travis-ci.org/Swyfee/Projet-1/builds/496966629
Github: https://github.com/Swyfee/Projet-1

**Comment by L-Co-P** [comment]
Loann Peurey

CI : https://travis-ci.org/L-Co-P/LPA2/builds/496967595

github : https://github.com/L-Co-P/LPA2

**Comment by vareversat** [comment]
CI : https://travis-ci.org/vareversat/UTBM-Web-Project/builds/496968165

Github : https://github.com/vareversat/UTBM-Web-Project

**Comment by AppliNH** [comment]
/ THOMAS MARTIN / 

Repo github : https://github.com/AppliNH/utbm-webproject1

CI : https://travis-ci.com/AppliNH/utbm-webproject1/builds/101914907

/ THOMAS MARTIN /

**Comment by macdrien** [comment]
CI: https://travis-ci.com/macdrien/LP71_projet_ruby_on_rails/builds/101986486
Github: https://github.com/macdrien/LP71_projet_ruby_on_rails

**Comment by MohamedCA2018** [comment]
**Mohamed El Guendouz** 

GitHub : https://github.com/MohamedCA2018/LPA2

CI : https://travis-ci.org/MohamedCA2018/LPA2/builds/496971966

**Comment by vtison** [comment]
TISON Victor

CI: https://travis-ci.org/vtison/LP71-LPA2-project-utbm/builds/497501667

GitHub: https://github.com/vtison/LP71-LPA2-project-utbm

**Comment by Oxyh** [comment]
Adrien Devaux

GithUb: https://github.com/Oxyh/LP71-Projet1-Ruby

CI: https://travis-ci.org/Oxyh/LP71-Projet1-Ruby/builds/497744243

**Comment by Julienm25** [comment]
Julien Mauvais

GithUb: https://github.com/Julienm25/LP71

CI: https://travis-ci.org/Julienm25/LP71/builds/498181459

**Comment by RemiPapillier** [comment]
Rémi Papillier

GitHub: https://github.com/RemiPapillier/Project_Rails
CI: https://travis-ci.org/RemiPapillier/Project_Rails/builds/498231154

**Comment by Joan68** [comment]
Joan Frey

GitHub: https://github.com/Joan68/multimedia-lesson
CI: https://travis-ci.org/Joan68/multimedia-lesson/builds/496970802

**Comment by S-HENR** [comment]
GitHub: https://github.com/S-HENR/Projet
CI : https://travis-ci.org/S-HENR/Projet/builds/498776674

**Comment by Clau-G** [comment]
Claudia Gauthier

CI : https://travis-ci.org/Clau-G/LP71_project/builds/498806855
GitHub : https://github.com/Clau-G/LP71_project

**Comment by BHemez** [comment]
Brieuc HEMEZ

CI : https://travis-ci.org/BHemez/LP71-LPA2/builds/498876754
GitHub : https://github.com/BHemez/LP71-LPA2

**Comment by PantchoL** [comment]
Lucas PANTCHENKO

CI : https://travis-ci.org/PantchoL/LPA2/builds/498988519
GitHub : https://github.com/PantchoL/LPA2

**Comment by MangeTonChat** [comment]
Valentin QUIGUER

CI : https://travis-ci.org/MangeTonChat/APP/builds/499144825
Github : https://github.com/MangeTonChat/APP

**Comment by fhenriot** [comment]
Fabien Henriot 
CI : https://travis-ci.org/fhenriot/projet-LP71/builds/499354634
GitHub : https://github.com/fhenriot/projet-LP71

**Comment by MPantcho** [comment]
Mathieu PANTCHENKO
CI : https://travis-ci.org/MPantcho/LPA2/builds/499508885
GitHub : https://github.com/MPantcho/LPA2

**Comment by vgalin** [comment]
CI: https://travis-ci.org/vgalin/app-rails-lp2a/builds/499767301
GitHub: https://github.com/vgalin/app-rails-lp2a

**Comment by Holdem67** [comment]
koukou c moi antoin
CI : https://travis-ci.org/Holdem67/LP71UTBM-Project/builds/499940178
GitHub : https://github.com/Holdem67/LP71UTBM-Project

**Comment by admo-1** [comment]
Adil Mohammad

CI : https://travis-ci.org/admo-1/RubyProject/builds/500075828
GitHub : https://github.com/admo-1/RubyProject

**Comment by LPA2-Automne2016** [comment]
Corrigé, OK
