### ISSUE TITLE
créer un controller student ( nom, date de naissance ) et déployer

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet-back-P2019#2]
générer un scaffold student avec comme attributs:
- name
- birthday ( date )

https://guides.rubyonrails.org/command_line.html#rails-generate

déployer vers héroku:
https://github.com/travis-ci/travis.rb#setup 
ATTENTION à sqlite !!! pensez à le remplacer par pg !!

poster ici: 

- le lien vers le build travis
- le lien vers votre page student dans heroku

**Comment by Oxyh** [comment]
Adrien Devaux

Lien travis: https://travis-ci.org/Oxyh/appv2/builds/503759649

Lien heroku: https://lp71v2.herokuapp.com/

**Comment by Julienm25** [comment]
Travis:
https://travis-ci.org/Julienm25/LP71/builds/503771989
Heroku :
https://lp71-julien.herokuapp.com/

**Comment by Joan68** [comment]
Travis : 
https://travis-ci.org/Joan68/On-Recommence/builds/503756742
Heroku :
https://protected-thicket-81658.herokuapp.com/

**Comment by vareversat** [comment]
Travis:
https://travis-ci.org/vareversat/UTBM-Web-Project/builds/503784932

Heroku:
https://utbm-web-project.herokuapp.com/

**Comment by macdrien** [comment]
Adrien Bouyssou:
GitHub : https://github.com/macdrien/LP71_web_ruby_on_rails
Travis : https://travis-ci.com/macdrien/LP71_web_ruby_on_rails/builds/103539129
Heroku : https://lp71-web-ruby-on-rails-project.herokuapp.com/
Pour heroku l'application build correctement mais crash au lancement.

**Comment by RemiPapillier** [comment]
Travis:
https://travis-ci.org/RemiPapillier/Project_Rails/builds/503789492

Heroku:
https://railspapillier.herokuapp.com/
https://railspapillier.herokuapp.com/students
Can't access students

**Comment by AppliNH** [comment]
Thomas M

Pour ma part, et comme pour les 3/4 de la classe, j'ai suivi différents tutos dans tous les sens. 
Et je pense avoir eu le chance, car j'ai pu compléter une bonne partie de ce que vous demandiez.

Néanmoins, je considère ne pas vraiment maîtriser toute cette configuration que j'ai réalisé, car j'ai été incapable de venir en aide à des camarades dans le besoin.
De mon point de vue, je ne peux pas vous rendre un travail que je n'ai pas compris.

Ce qui est certain ce que nous avons bossé toute la semaine dessus (ensemble) et que nous aurons **tous** besoin d'un grand moment d'explication/correction demain.

Je posterais mes liens Travis et Heroku dès j'aurais tout compris, après des explications demain matin. Il me semble essentiel de maîtriser la configuration des outils que je vais utiliser.

Merci.
EDIT : Maintenant que j'ai compris :
TRAVIS : https://travis-ci.com/AppliNH/utbm-webproject1/builds/103772089
Heroku : https://utbmwebproject1.herokuapp.com/students/

Merci beaucoup pour les explications !

**Comment by Swyfee** [comment]
CI: https://travis-ci.org/Swyfee/Projet-1/builds/502631389
HEROKU: https://utbmprojet1.herokuapp.com/
Students non accessible

**Comment by vgalin** [comment]
Travis CI: https://travis-ci.org/vgalin/app-rails-lp2a/builds/503811288
Heroku app: https://app-rails-lp2a.herokuapp.com/

**Comment by MohamedCA2018** [comment]
Travis : https://travis-ci.com/MohamedCA2018/LP712019/builds/103670304

Heroku : https://lp712019.herokuapp.com

GitHub : https://github.com/MohamedCA2018/LP712019/commit/c0c2f91433206c42ea59760fca111630d762dfbf


J'ai changé de répertoire que j'ai appelé LP712019  car l'autre posé problème sur différents composants de l'app.

**Comment by fhenriot** [comment]
https://travis-ci.org/fhenriot/projet-LP71/builds/503855831
https://lp71-project-henriot.herokuapp.com/

**Comment by LPA2-Automne2016** [comment]
J'ai noté pour les bonii, c'est pris en compte !
