### ISSUE TITLE
Créer le backend pour les produits

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet-back-P2019#4]
contenu d'un produit :

- nom
- description
- prix 
- image

mettre en ligne et poster :
- le lien vers le build travis
- le lien vers la page des produits sous heroku

**Comment by RemiPapillier** [comment]
Travis:
https://travis-ci.org/RemiPapillier/Project_Rails/builds/503967178
Heroku:
https://railspapillier.herokuapp.com/products

**Comment by vtison** [comment]
Victor TISON

CI : https://travis-ci.org/vtison/LP71_TISON_1/builds/503965019

Heroku : https://lp71tison.herokuapp.com/produits

**Comment by admo-1** [comment]
Adil MOHAMMAD

[Build Travis (22)](https://travis-ci.org/admo-1/potential-potato/builds/503965606)
[Lien Heroku](https://potential-potato.herokuapp.com/products)

**Comment by Clau-G** [comment]
Claudia Gauthier

[travis (29)](https://travis-ci.org/Clau-G/LP71_project/builds/509515132) 
[heroku ](https://lp71-project.herokuapp.com/produits)

**Comment by S-HENR** [comment]
Séraphin HENRY

Build travis : https://travis-ci.org/S-HENR/Projet-pg/builds/503964645
Lien app Heroku : https://s-hen.herokuapp.com/produits

**Comment by L-Co-P** [comment]
Loann Peurey

travis : https://travis-ci.org/L-Co-P/LPA2/builds/503968005
heroku : https://peureyl-lpa2.herokuapp.com/produits

**Comment by GRazafy** [comment]
Gabriel Razafindratsima

[travis](https://travis-ci.org/GRazafy/RAILS/builds/503963716) 
[heroku](https://lpa2razafindratsima.herokuapp.com/produits/)

**Comment by AppliNH** [comment]
Thomas MARTIN

[Travis](https://travis-ci.com/AppliNH/utbm-webproject1/builds/103773651)
[Heroku](https://utbm-webproject1.herokuapp.com/products)

**Comment by vareversat** [comment]
Valentin REVERSAT

[Heroku](https://utbm-web-project.herokuapp.com/products)
[Travis](https://travis-ci.org/vareversat/UTBM-Web-Project/builds/505079616)

**Comment by BHemez** [comment]
[Travis](https://travis-ci.org/BHemez/LP71-LPA2/builds/505647250)
[Heroku](https://lp71-lpa2.herokuapp.com/produits)

**Comment by fhenriot** [comment]
[Travis](https://travis-ci.org/fhenriot/projet-LP71/builds/505641271)
[Heroku](https://lp71-project-henriot.herokuapp.com/)

**Comment by Skaopap** [comment]
Thominet Benjamin :

travis : https://travis-ci.org/Skaopap/UTBM_WORK_V3/builds/503974208

heroku : https://utbmworkv3.herokuapp.com/products

**Comment by MangeTonChat** [comment]
Valentin QUIGUER

Travis : https://travis-ci.org/MangeTonChat/APP/builds/505623311

Heroku : https://applicationzd.herokuapp.com/produits

**Comment by Julienm25** [comment]
[Heroku](https://lp71-julien.herokuapp.com/)
[Travis](https://travis-ci.org/Julienm25/LP71/builds/507861604)

**Comment by MohamedCA2018** [comment]
Mohamed El Guendouz

Travis CI : 
https://travis-ci.org/MohamedCA2018/LPA2/builds/508901320

GitHub :

Repertoire :
https://github.com/MohamedCA2018/LPA2  Commits :
https://github.com/MohamedCA2018/LPA2/commit/838afaf23e586811ba6eb18fa102d47a59f52045

Heroku :
Deploy : 838afaf2

Students : 
https://lpa2-2019.herokuapp.com/students

Product : 
https://lpa2-2019.herokuapp.com/products
https://lpa2-2019.herokuapp.com/products/1

**Comment by Holdem67** [comment]
Travis : https://travis-ci.org/Holdem67/RoRProject/builds/508982296 

Heroku : https://rorproject1.herokuapp.com/products

**Comment by PantchoL** [comment]
PANTCHENKO Lucas

Travis : https://travis-ci.org/PantchoL/LPA2/builds/508981871

Heroku : https://pantchol.herokuapp.com/produits

**Comment by Oxyh** [comment]
DEVAUX Adrien

Travis: https://travis-ci.org/Oxyh/appv2/builds/509019130

Heroku: https://lp71v2.herokuapp.com/products

**Comment by MPantcho** [comment]
Pantchenko Mathieu

Heroku : https://mpantcho.herokuapp.com/produits

Travis : https://travis-ci.org/MPantcho/LPA2/builds/509037882

**Comment by Swyfee** [comment]
Thibaut ROUSSEAUX
[Heroku](https://utbmprojet1.herokuapp.com/products)
[Travis](https://travis-ci.org/Swyfee/Projet-1/builds/509520712)

**Comment by vgalin** [comment]
Travis CI : https://travis-ci.org/vgalin/app-rails-lp2a/builds/509600163
Heroku App : https://app-rails-lp2a.herokuapp.com/products

**Comment by Joan68** [comment]
Joan Frey
Heroku : https://protected-thicket-81658.herokuapp.com/produits
Travis : https://travis-ci.org/Joan68/On-Recommence/builds/509605413

**Comment by LPA2-Automne2016** [comment]
Bon boulot à tous, j'ai bien ri avec vos photos !
Il y en a qui se sont fait plaisir !
