### ISSUE TITLE
mettre en place le modele pour les commandes

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet-back-P2019#6]
A partir du swagger ci dessous:

```
openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/LPA2-Automne2016/commandes/1.0.0
info:
  description: This is a simple Order API
  version: "1.0.0"
  title: Simple order API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: orders
    description: orders related
paths:
  /orders:
    post:
      tags:
        - orders
      summary: creates an order
      operationId: createOrder
      description: creates an order to the system
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        description: Inventory item to add
components:
  schemas:
    Order:
      type: object
      properties:
        name:
          type: string
          example: Luc Skywalker
        adress:
          type: string
          example: 3 rue des alouettes
        town:
          type: string
          example: Belfort
        zipcode:
          type: string
          example: "9000"
        products:
          type: array
          items:
            type: number
          example: 
            - 123
            - 679
      ```

Créer le modele ainsi que les migrations pour permettre d'accueillir les commandes.

déployer sous heroku, poster CI

**Comment by RemiPapillier** [comment]
CI Rémi:
https://travis-ci.org/RemiPapillier/Project_Rails/builds/510049831

**Comment by RemiPapillier** [comment]
Remi Papillier CI:
https://travis-ci.org/RemiPapillier/Project_Rails/builds/511190010

**Comment by Julienm25** [comment]
Travis : 
https://travis-ci.org/Julienm25/LP71/builds/510937744
Heroku :
https://lp71-julien.herokuapp.com/

**Comment by AppliNH** [comment]
Thomas Martin

[Travis](https://travis-ci.org/AppliNH/utbm-webproject1/builds/510964146)

**Comment by S-HENR** [comment]
Séraphin HENRY
[Travis](https://travis-ci.org/S-HENR/Projet-pg/builds/511458304)

**Comment by Clau-G** [comment]
Claudia G

[Travis](https://travis-ci.org/Clau-G/LP71_project/builds/511463702)

**Comment by vareversat** [comment]
Valentin REVERSAT

Heroku : http://heroku.kebab-hurlant.fr
[Travis](https://travis-ci.org/vareversat/UTBM-Web-Project/builds/511470203)

**Comment by Joan68** [comment]
Joan Frey

CI : https://travis-ci.org/Joan68/On-Recommence

**Comment by Swyfee** [comment]
Thibaut ROUSSEAUX
[CI](https://travis-ci.org/Swyfee/Projet-1/builds/511458146)

**Comment by Oxyh** [comment]
Adrien Devaux

CI: https://travis-ci.org/Oxyh/appv2/builds/512047166

**Comment by BHemez** [comment]
[Travis](https://travis-ci.org/BHemez/LP71-LPA2/builds/512045852)

**Comment by L-Co-P** [comment]
Loann Peurey
https://travis-ci.org/L-Co-P/LPA2/builds/512413279

**Comment by Holdem67** [comment]
https://travis-ci.org/Holdem67/RoRProject/builds/513150527

**Comment by PantchoL** [comment]
PANTCHENKO Lucas

https://travis-ci.org/PantchoL/LPA2/builds/513162454

**Comment by vgalin** [comment]
https://travis-ci.org/vgalin/app-rails-lp2a/builds/513169838

**Comment by MangeTonChat** [comment]
https://travis-ci.org/MangeTonChat/APP/builds/513184778

**Comment by MPantcho** [comment]
PANTCHENKO Mathieu

https://travis-ci.org/MPantcho/LPA2/builds/513183921

**Comment by MohamedCA2018** [comment]
Mohamed El Guendouz 

Travis : https://travis-ci.com/MohamedCA2018/LPA2/builds/106382572

**Comment by Skaopap** [comment]
benjamin thominet

https://travis-ci.org/Skaopap/UTBM_WORK_V3/builds/513208757

**Comment by GRazafy** [comment]
Gabriel Razafindratsima

[Travis](https://travis-ci.org/GRazafy/RAILS/builds/513243830)

**Comment by admo-1** [comment]
Adil Mohammad
[Travis ](https://travis-ci.org/admo-1/potential-potato/builds/513228062)

**Comment by fhenriot** [comment]
Travis : https://travis-ci.org/fhenriot/projet-LP71/builds/510898172

**Comment by LPA2-Automne2016** [comment]
OK
